### ISSUE TITLE
Axon plugin 0.8.0 is not supported by IDEA 2023.1

### ISSUE THREAD

**Issue by KDanisme** [AxonFramework/IdeaPlugin#190] opened 2023-03-29 12:51 UTC
Enhancement Description
Axon plugin 0.8.0 is not supported by IDEA 2023.1

Running:
IntelliJ IDEA 2022.3 (Ultimate Edition)
Build #IU-231.8109.175, built on March 28, 2023

Current Behaviour
Error:
```Plugin 'Axon Framework' (version '0.8.0') is not compatible with the current version of the IDE, because it requires build 223.* or older but the current build is IU-231.8109.175```

**Comment by Morlack** [comment] 2023-03-29 16:40
Hello @KDanisme, thanks for letting me know. I have just pushed an update to the repository that will be published to Intellij plugin repository. It can take some time to get approved by Jetbrains before it's available

**Comment by Morlack** [comment] 2023-03-29 16:42
Unfortunately Github Actions is also down, so the release will hopefully work later today

**Comment by Morlack** [comment] 2023-03-30 15:05
@KDanisme I just pushed an updated version of the plugin. It's availability will depend on approval speed of Jetbrains (can officially take 3 days, often takes a couple of hours)

**Comment by Morlack** [comment] 2023-03-30 15:18
You can also download the plugin here and install it into your IDEA: https://github.com/AxonFramework/IdeaPlugin/releases/tag/v0.8.1

**Comment by KahigaKiguru** [comment] 2023-03-30 16:02
@Morlack @KDanisme I can confirm the issue has ben resolved. The plugin is now supported by IntelliJ 2023.1

**Comment by Morlack** [comment] 2023-03-31 06:43
Great! Closing the issue since it's resolved

**Closed by Morlack** 2023-03-31 06:43 UTC
Labels: Type: Enhancement, Status: Blocked, Priority 1: Must

**Comment by CodeDrivenMitch** [comment] 2023-07-31 01:25
Hello @meierw, I believe you are referring to the new 2023.2/0.8.2 versions. I will check the reports and create a fix
